### ISSUE TITLE
Will you be updating AdvGen3 to 1.7.10

### ISSUE THREAD

**Issue by phantomtiger** [TinyModularThings/TinyModularThings#16]
I really love your mods and noticed you said you are working on updating SpmodAPI and TinyChest, I am curious if you are also working on updating AdvGen3, too. I quite enjoy the mods and would love to add them to my 1.7.10 industrial craft based world. Thanks!

**Comment by Speiger** [comment]
AdvGen3 will be updated with TinyChest together.
How long that takes i can not make any promises.
SpmodAPI is almost done^^ 80-90%
