### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TTLPcraft** [TinyModularThings/TinyModularThings#17]
[B#347]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#347]  ---------------------------------------------------------------------------------------
[B#347]  
[B#347]  -- System Details --
[B#347]  Details:
[B#347]  	Minecraft Version: 1.7.10
[B#347]  	Operating System: Windows 10 (amd64) version 10.0
[B#347]  	Java Version: 1.8.0_66, Oracle Corporation
[B#347]  	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[B#347]  	Memory: 15532423168 bytes (14812 MB) / 16106127360 bytes (15360 MB) up to 16106127360 bytes (15360 MB)
[B#347]  	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms15360m -Xmx15360m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
[B#347]  	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[B#347]  	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[B#347]  	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 4 mods loaded, 4 mods active
[B#347]  	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[B#347]  	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
[B#347]  	UC	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
[B#347]  	UC	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
[B#347]  	UE	SpmodAPI{2.0.1} [SpmodAPI-Beta] (SpmodAPI Version 1.3.12.zip) 
[B#347]  	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GPU/PCIe/SSE2'
[B#347]  [13:59:33] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\TTLP\OneDrive\alpha console\technic\technic\modpacks\tekkit-legends\crash-reports\crash-2016-02-04_13.59.33-client.txt

**Comment by Speiger** [comment]
@TTLPcraft this version of SpmodAPI is dead.. It was a remake version of the 1.4.7 version. and also it was made for 1.6.4 and not 1.7.10^^"
The current 1.7.10 version not released yet and still in beta testing xD
