### ISSUE TITLE
QuantumPack server side

### ISSUE THREAD

**Issue by SvEgiiVEteR** [TinyModularThings/TinyModularThings#20]
https://gist.github.com/e5db842754de1a17aebad0489fba5c2c

**Comment by Speiger** [comment]
@SvEgiiVEteR could you give me a couple days to fix it? (Simply i try to prioritize all my stuff to classic 1.9) or do you need it tomorrow (my day is almost over so today nothing)

**Comment by SvEgiiVEteR** [comment]
@Speiger yes of course, I don't hurry)
it is strange that I reported one about a mistake

**Comment by Speiger** [comment]
@SvEgiiVEteR thanks. Yeah its a stupid derp bug when i converted that mod...
At least you are the reason why SpmodAPi also gets a update with a new feature (to enable modules and that mods can request modules)

**Comment by Speiger** [comment]
Updates comes after a little test

**Comment by Speiger** [comment]
@SvEgiiVEteR SpmodAPI will gain a new feature thanks to you.
Modules. So you can enable and dissable components. (Addons request required  components and  forces the mod to load them (So no worry about crashing a addon))

**Comment by SvEgiiVEteR** [comment]
thank you now it works)
